Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'jenkis'
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip:'127.0.0.1'
  config.vm.network "private_network", ip: "192.165.1.5"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true } 
  config.vm.provider 'virtualbox' do |v|
    v.memory = 2024
  end

  
end
