Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "k8s-master"
  config.vm.network "private_network", ip: "192.167.1.2"
  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider 'virtualbox' do |v|
    v.memory = 3072
    v.cpus = 2
  end
end
