apiVersion: v1
kind: Pod
metadata:
  name: pod-init
spec:
  initContainers:
    - name: init-1
      image: busybox
      command: ["echo", "i am init-1"]
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    - name: init-2
      image: busybox
      command: ["sleep", "30"]
  containers:
    - name: main-app
      image: busybox
      command: ["sleep", "30"]
  restartPolicy: Never