apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: busybox-container-2
      image: busybox
      command: ["sleep", "1d"]
  restartPolicy: Never