Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.167.1.2"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true } 
end