- name: Upgrade de todos os pacotes do s.o
  yum:
    name: "*"
    state: latest

- name: 
  yum:
    name: git
    state: latest

- name: Configurar hosts lab ansible
  lineinfile: 
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items:
    - 192.167.1.2 control-node
    - 192.167.1.3 app01
    - 192.167.1.4 db01    
