Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'manager'
  config.vm.network "private_network", ip: "192.165.1.2"
  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true } 
  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
  end

end
