# Deployment do Postgree
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.3
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef: 
                name: database-creds
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-creds
                key: password
          - name: POSTGRES_DB
            value: "kubenews"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: jordanvieira/kube-news:v1
        env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-creds
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-creds
                key: password
          - name: DB_HOST
            value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubenews
spec:
  ingressClassName: traefik
  rules:
  - host: "www.172.18.0.1.sslip.io"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kubenews
              port:
                number: 80

