Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "worker1"
  config.vm.network "private_network", ip: "192.167.1.3"
  config.vm.provider 'virtualbox' do |v|
    v.memory = 3072
    v.cpus = 2
  end
end