# Criação de um service com o nome service-web utilizando nodePort: 30000
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: web
  ports:
  - port: 80
    nodePort: 30000
  type: NodePort
  