apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: {{ .Values.web.serviceType }}